services:
  - type: static
    name: stickman-animation
    runtime: static
    buildCommand: ""
    staticPublishPath: ./
    pullRequestPreviews: false
    plan: free
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
